In [ ]:
# 1.SORUNUN CEVABI 

In [111]:
import numpy as np

In [52]:
array = np.array([5, 70, 56, 85, 42, 46, 69, 85, 41, 37], dtype=int)

In [53]:
type(array)

numpy.ndarray

In [54]:
array_size = array.size

In [55]:
print("Arrayin eleman sayısı (size):", array_size)

Arrayin eleman sayısı (size): 10


In [56]:
# 2.SORUNUN CEVABI

In [57]:
# 2 boyutlu dizi oluşturduk.
array_2d = np.array([[4, 8, 7], [3, 5, 2], [9, 4, 5]], dtype=int)

print("İki boyutlu array:\n", array_2d)  

İki boyutlu array:
 [[4 8 7]
 [3 5 2]
 [9 4 5]]


In [58]:
# 3 boyutlu dizi oluşturduk.
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                     [[7, 8, 9], [10, 11, 12]], 
                     [[13, 14, 15], [16, 17, 18]]], dtype=int)

print("Üç boyutlu array:\n", array_3d)  

Üç boyutlu array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [59]:
# oluşturduğumuz dizilerin boyutları
array_2d_shape = array_2d.shape
array_3d_shape = array_3d.shape

print("İki boyutlu arrayin boyutu (shape):", array_2d_shape)
print("Üç boyutlu arrayin boyutu (shape):", array_3d_shape)

İki boyutlu arrayin boyutu (shape): (3, 3)
Üç boyutlu arrayin boyutu (shape): (3, 2, 3)


In [60]:
# oluşturduğumuz dizinin eleman sayıları
array_2d_size = array_2d.size
array_3d_size = array_3d.size

print("İki boyutlu arrayin eleman sayısı (size):", array_2d_size)
print("Üç boyutlu arrayin eleman sayısı (size):", array_3d_size)

İki boyutlu arrayin eleman sayısı (size): 9
Üç boyutlu arrayin eleman sayısı (size): 18


In [61]:
# 2 boyutlu dizinin satır ve sütun sayısı
array_2d_rows = array_2d.shape[0]
array_2d_cols = array_2d.shape[1]

print("İki boyutlu arrayin satır sayısı (rows):", array_2d_rows)
print("İki boyutlu arrayin sütun sayısı (columns):", array_2d_cols)

İki boyutlu arrayin satır sayısı (rows): 3
İki boyutlu arrayin sütun sayısı (columns): 3


In [63]:
# 3 boyutlu dizinin satır ve sutün sayıları
array_3d_rows = array_3d.shape[0]
array_3d_cols = array_3d.shape[1]

print("Üç boyutlu arrayin satır sayısı (rows):", array_3d_rows)
print("Üç boyutlu arrayin sutün sayısı (columns):", array_3d_cols)

Üç boyutlu arrayin satır sayısı (rows): 3
Üç boyutlu arrayin sutün sayısı (columns): 2


In [68]:
#  2.satır 3.elemanı verir
array_2d[1, 2]

2

In [77]:
# 2.katman 2.satır 2.sutün elemanını verir.
array_3d[1, 1, 1]

11

In [78]:
# 3.SORUNUN CEVABI 

In [81]:
# 1 boyutlu dizi oluşturduk.
dizi_1 = np.array([1, 2, 3, 4, 5])
print("Bir boyutlu dizi:")
print(dizi_1)

Bir boyutlu dizi:
[1 2 3 4 5]


In [86]:
# 2 boyutlu dizi oluşturduk.
dizi_2 = np.array([[5,6,3], [8,9,6],[3,7,5]])
print(" İki boyutlu dizi: ")
print(dizi_2)

 İki boyutlu dizi: 
[[5 6 3]
 [8 9 6]
 [3 7 5]]


In [90]:
# 3 boyutlu dizi oluşturalım. 
dizi_3 = np.array([[[2,3,6],[8,7,5]],[[2,5,9],[7, 8, 9]]])
print("Üç boyutlu dizi: ")
print(dizi_3)

Üç boyutlu dizi: 
[[[2 3 6]
  [8 7 5]]

 [[2 5 9]
  [7 8 9]]]


In [94]:
array_1[0]

1

In [95]:
array_2d[1, 2]

2

In [96]:
array_3d[0, 1, 2]

6

In [114]:
# sıfırlardan oluşan iki boyutlu dizimizi oluşturduk
sifir_array = np.zeros((3, 3))
print("Sıfırlardan oluşan iki boyutlu array:")
print(sifir_array)

Sıfırlardan oluşan iki boyutlu array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [115]:
# birlerden oluşan iki boyutlu dizimiz
birler_array = np.ones((3, 3))
print("\nBirlerden oluşan iki boyutlu array:")
print(ones_array)


Birlerden oluşan iki boyutlu array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [116]:
# satırları birleştirdik.
vertical_stack = np.vstack((zeros_array, ones_array))
print("\nSatır bazında birleştirilen array:")
print(vertical_stack)


Satır bazında birleştirilen array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [118]:
# sutün olarak birleştirirsek
horizontal_stack = np.hstack((zeros_array, ones_array))
print("\nSütun bazında birleştirilen array:")
print(horizontal_stack)


Sütun bazında birleştirilen array:
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
